name: Test (scratch)

on:
  push:

jobs:
  test-scratch:
    runs-on: ubuntu-latest
    steps:
    - name: fail earlier (fail whole job)
      run: exit 1
    - name: This might fail, but I don't want it to mark the workflow bad
      id: badstep
      continue-on-error: true
      run: exit 1
    - name: I want this to run even if step 1 fails
      if: ${{ steps.badstep.outcome == 'failure' }}
      run: echo "I'm running despite continue (I think this won't work)"
