name: Test (scratch)

on:
  push:

jobs:
  test-scratch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      id: badstep
      continue-on-error: true
      run: exit 1
    - name: How is `failure()` treated?
      if: ${{ failure() || steps.badstep.outcome != 'failure' }}
      run: echo I'm running despite continue (I think this won't work)
